### ISSUE TITLE
"istiod" not found

### ISSUE THREAD

**Issue by baraklior** [PrefectHQ/prefect-helm#220] opened 2023-08-07 08:42 UTC
i'm installing the helm charts on EKS and getting this error:

`create Pod prefect-server-postgresql-0 in StatefulSet prefect-server-postgresql failed error: Internal error occurred: failed calling webhook "namespace.sidecar-injector.istio.io": failed to call webhook: Post "https://istiod.istio-system.svc:443/inject?timeout=10s": service "istiod" not found`

none of the prefect pods are up
Kubernetes version 1.22

**Comment by jamiezieziula** [comment] 2023-08-11 19:24
Hi @baraklior - this isn't caused by the chart installation. It's likely that you have previously installed istio into the EKS cluster and you're missing some dependency now (istiod). I'd check the namespace you're attempting to install the helm chart to to see if its labeled for istio injection. Closing as its not related to the chart.

**Closed by jamiezieziula** 2023-08-11 19:24 UTC
